name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to test'
        required: true
        default: 'test'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=omercengel/port-scanner
          VERSION_TAG=${{ github.event.inputs.version }}
          
          docker build -t $IMAGE_NAME:$VERSION_TAG .
          
          docker tag $IMAGE_NAME:$VERSION_TAG $IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          IMAGE_NAME=omercengel/port-scanner
          VERSION_TAG=${{ github.event.inputs.version }}
          docker push $IMAGE_NAME:$VERSION_TAG
          docker push $IMAGE_NAME:latest
